### ISSUE TITLE
Сверстать главную страницу

### ISSUE THREAD

**Issue by hikjik** [hikjik/movies-explorer-frontend#2]
## Список компонентов главной страницы:
- [x] [Сверстать блок Promo](https://github.com/hikjik/movies-explorer-frontend/issues/3);
- [x] [Сверстать блок AboutProject](https://github.com/hikjik/movies-explorer-frontend/issues/4);
- [x] [Сверстать блок Techs](https://github.com/hikjik/movies-explorer-frontend/issues/5);
- [x] [Сверстать блок AboutMe](https://github.com/hikjik/movies-explorer-frontend/issues/6);
- [x] [Сверстать блок Portfolio](https://github.com/hikjik/movies-explorer-frontend/issues/7).

## Общие компоненты:
- [x] [Сверстать Header](https://github.com/hikjik/movies-explorer-frontend/issues/8);
- [x] [Сверстать Navigation](https://github.com/hikjik/movies-explorer-frontend/issues/9);
- [x] [Сверстать Footer](https://github.com/hikjik/movies-explorer-frontend/issues/10).
